Rules:
# Leave environment value empty so the rule applies to any environment (if no match for a specific environment is found)
- Environment:
  # Search is more expensive and has a very low rate limit. Use wisely.
  Search:
    MaxAllowed: 0
    # Message: You have too many open show stoppers # (optional)
    Query: 'is:open repo:bbq-beets/protection-rules-playground label:show-stopper'
    OnlyCreatedBeforeWorkflowCreated: true

# Local env
- Environment: production
  # Time to wait until the gate is evaluated
  # WaitMinutes: 5
  Issues:
    MaxAllowed: 0
    # Message: You have too many open show stopper bugs # (optional)    
    State: "OPEN"
    # Repo:  # If omitted current repo will be used
    # Assignee: ""
    # Author: ""
    # Mention: ""
    # Skip Milestone parameter or * for any milestone, value for a specific milestone (NUMBER not label) 
    # Milestone: "1" # Milestone number (not label)
    Labels:
      - BUG
      - show-stopper
    OnlyCreatedBeforeWorkflowCreated: true
