name: Cleanup PR
on:
  pull_request:
    types: [closed]
    branches: main

permissions:
  contents: read
  
jobs:
  delete-review-slot:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Delete deployment slot
      continue-on-error: true
      run: |
        az webapp deployment slot delete  --name popular-repos --slot review-pr-${{ github.event.number }}  --resource-group ${{ vars.AZURE_RESOURCE_GROUP }}
