name: Deploy Site
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Setup node 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12.x'

    - name: Cache node modules
      id: cache-node
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: steps.cache-node.outputs.cache-hit != 'true'
      run: |
        npm install --silent

    - name: Build site
      run:  npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to Container Registry
      run: az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.AZURE_REGISTRY_NAME }}/popular-repos:${{ github.event.pull_request.head.sha || github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy_to_review:
    name: Deploy Review
    if: github.event_name == 'pull_request'
    needs: build
    uses: ./.github/workflows/shared-deploy.yaml@main
    with:
      app_name: popular-repos
      app_id: popular-repos-web
      environment_name: review-lab
      environment_url: ${{ steps.popular-repos-web.outputs.webapp-url }}
      pr_number: github.event.number
      sha: github.event.pull_request.head.sha

  deploy_to_staging:
    name: Deploy Staging
    if: github.event.ref == 'refs/heads/main'
    needs: build
    uses: ./.github/workflows/shared-deploy.yaml@main
    with:
      app_name: popular-repos
      app_id: popular-repos-web
      environment_name: staging
      environment_url: ${{ steps.popular-repos-web.outputs.webapp-url }}
      pr_number: ''
      sha: github.sha

  deploy_to_production:
    name: Deploy Production
    if: github.event.ref == 'refs/heads/main'
    needs: deploy_to_staging
    uses: ./.github/workflows/shared-deploy.yaml@main
    with:
      app_name: popular-repos
      app_id: popular-repos-web
      environment_name: production
      environment_url: https://popular-repos.azurewebsites.net
      pr_number: ''
      sha: github.sha
