name: Deploy Site Reusable
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  code-analysis:
    uses: bbq-beets/workflows/.github/workflows/code-analysis.yml@main
    with:
      languages: 'javascript'
      
  build-deploy:
    name: Deploy App
    uses: ./.github/workflows/shared-build-deploy.yaml
    with:
      app-name: ${{ vars.AZURE_WEB_APP }}
      app-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
      AZURE_REGISTRY_NAME: ${{ vars.AZURE_REGISTRY_NAME }}
    secrets: inherit
